# Exercise real CLI parsing/scripts, persistent reopen, and safe export. Only
# this test's freshly created temporary directory is ever removed.
string(RANDOM LENGTH 20 ALPHABET 0123456789abcdef test_id)
set(test_directory "${TEMP_ROOT}/mint-headless-test-${test_id}")
if(EXISTS "${test_directory}")
    message(FATAL_ERROR "temporary test directory collision")
endif()
file(MAKE_DIRECTORY "${test_directory}")
file(SHA256 "${INPUT}" original_hash)
execute_process(COMMAND "${TOOL}" "${INPUT}" --project "${test_directory}/program.mint" --script "${SCRIPT}" export-patched "${test_directory}/patched binary.so" RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    file(REMOVE_RECURSE "${test_directory}")
    message(FATAL_ERROR "headless script/export failed: ${output}\n${errors}")
endif()
execute_process(COMMAND "${TOOL}" "${INPUT}" --project "${test_directory}/program.mint" json RESULT_VARIABLE result OUTPUT_VARIABLE json ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
    file(REMOVE_RECURSE "${test_directory}")
    message(FATAL_ERROR "headless reopen failed: ${errors}")
endif()
string(JSON name GET "${json}" functions 0 name)
string(JSON origin GET "${json}" functions 0 origin)
file(SHA256 "${INPUT}" after_hash)
file(SHA256 "${test_directory}/patched binary.so" patched_hash)
execute_process(COMMAND "${TOOL}" "${INPUT}" --project "${test_directory}/program.mint" export-patched "${INPUT}" RESULT_VARIABLE overwrite OUTPUT_QUIET ERROR_QUIET)
file(SHA256 "${INPUT}" final_hash)
execute_process(COMMAND "${TOOL}" "${INPUT}" unsupported-command RESULT_VARIABLE invalid OUTPUT_QUIET ERROR_QUIET)
file(REMOVE_RECURSE "${test_directory}")
if(NOT name STREQUAL "headless_entry" OR NOT origin STREQUAL "user" OR NOT original_hash STREQUAL after_hash OR NOT original_hash STREQUAL final_hash OR original_hash STREQUAL patched_hash OR overwrite EQUAL 0 OR invalid EQUAL 0)
    message(FATAL_ERROR "headless persist/export/fail-fast contract failed")
endif()
message(STATUS "Headless scripts, cold reopen, JSON, spaced export path and source/overwrite guards passed")
