#!/usr/bin/env python3
"""Approved Mint leaf/graph: SVG masters and adaptive Android vectors."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GREEN = "#53DB9C"
BACKGROUND = "#10251D"
PATH = ("M128 32 C148 44 164 64 172 86 L164 94 L180 110 H168 L180 122 "
        "H168 L176 130 L168 138 V160 C162 179 151 192 136 199 V224 H120 "
        "V199 C105 192 94 179 88 160 V138 L80 130 L88 122 H76 L88 110 "
        "H76 L92 94 L84 86 C92 64 108 44 128 32 Z M120 184 H136 V150 "
        "L152 134 H162 V110 H138 V134 L136 136 V98 H140 V74 H116 V98 "
        "H120 V144 L114 138 V128 H94 V152 H114 L120 158 Z")


def mark(colour=GREEN):
    return ('<g transform="translate(128 128) scale(1.12) rotate(45) '
            f'translate(-128 -128)"><path fill="{colour}" '
            f'fill-rule="evenodd" d="{PATH}"/></g>')


def svg(background=None, monochrome=False, show_safe=False, tile=None):
    # Adaptive canvas 384 units = 108dp; the central 256 units = visible 72dp.
    # Safe radius 66dp/2 = 117.33 units, larger than the artwork radius 107.52.
    size = 384 if show_safe else 256
    result = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" '
              f'height="{size}" viewBox="0 0 {size} {size}">',
              '<title>Mint — graph in a mint leaf</title>']
    if background:
        if tile == "round":
            result.append(f'<circle cx="128" cy="128" r="128" fill="{background}"/>')
        else:
            radius = 56 if tile == "rounded" else 0
            result.append(f'<rect width="{size}" height="{size}" rx="{radius}" '
                          f'fill="{background}"/>')
    if show_safe:
        result += ['<circle cx="192" cy="192" r="117.333" fill="none" '
                   'stroke="#ff0066" stroke-width="1"/>',
                   '<g transform="translate(64 64)">']
    result.append(mark("#000000" if monochrome else GREEN))
    if show_safe:
        result.append('</g>')
    return "\n".join(result + ['</svg>']) + "\n"


def vector_drawable(monochrome=False):
    colour = "#FF000000" if monochrome else GREEN
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by examples/make_logo.py; graph holes survive themed-icon tinting. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="384" android:viewportHeight="384">
    <group android:translateX="64" android:translateY="64">
        <group android:pivotX="128" android:pivotY="128"
            android:scaleX="1.12" android:scaleY="1.12" android:rotation="45">
            <path android:fillColor="{colour}" android:fillType="evenOdd"
                android:pathData="{PATH}" />
        </group>
    </group>
</vector>
'''


def main():
    variants = {
        "logo.svg": svg(),
        "logo-preview.svg": svg(background=BACKGROUND),
        "logo-safe.svg": svg(background=BACKGROUND, show_safe=True),
        "logo-mono.svg": svg(monochrome=True),
        "logo-icon.svg": svg(background=BACKGROUND, tile="rounded"),
        "logo-round.svg": svg(background=BACKGROUND, tile="round"),
    }
    for name, content in variants.items():
        (ROOT / "examples" / name).write_text(content, encoding="utf-8")
    for name, mono in (("ic_launcher_foreground.xml", False),
                       ("ic_launcher_monochrome.xml", True)):
        (ROOT / "app/src/main/res/drawable" / name).write_text(
            vector_drawable(mono), encoding="utf-8")
    (ROOT / "app/src/main/res/values/ic_launcher_background.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
        '    <!-- Approved Mint icon background. -->\n'
        f'    <color name="ic_launcher_background">{BACKGROUND}</color>\n'
        '</resources>\n', encoding="utf-8")
    print("Generated approved Mint SVGs and adaptive vectors.")


if __name__ == "__main__":
    main()
